[flake8]
extend-ignore = 
  # closing bracket does not match visual indentation
  E124,
  # visually indented line with same indent as next logical line
  E129,
  # whitespace after '(', '['
  E201,
  # whitespace before ')', ']'
  E202,
  # whitespace before ':', ',' 
  E203,
  # multiple spaces before operator
  E221,
  # multiple spaces after operator
  E222,
  # missing whitespace after ...
  E231,
  # unexpected spaces around keyword / parameter equals
  E251,
  # multiple spaces before keyword
  E272,
  # expected 2 blank lines, found ...
  E302,
  # too many blank lines
  E303,
  # expected 2 blank lines after class or function definition
  E305,
  # line too long
  E501, 
  # function too complex
  C901, 
  # imported but unused
  F401,
  # assigned to but never used
  F841,
exclude = .git,.claude,__pycache__,submodules,templates/umap/maki,templates/umap/osmic
max-complexity = 50
# deal with dynamically injected _() translation function
builtins = _
